% This is an autogenerated sample test for file STLExtractor.m
classdef testSTLExtractor < matlab.unittest.TestCase

    methods (Test)

        function test_process(testCase)
            % Specify the input(s) of
            % STLExtractor
            filename = "tests/test_stl_files/hex_r25_h5_o0p00_0p00_1p00.stl";
            workingDir = "tests/test_output";
            obj = STLExtractor(filename, workingDir);

            % Specify the expected output(s) of
            % STLExtractor/process
            [radius, thickness, normal, position] = parse_filename(filename);
            expected_l = HexagonalPrism(position,radius,thickness,normal);

            % Exercise the function obj.process
            actual_l = obj.process();

            testCase.verifyEqual(actual_l, expected_l);
        end
    end
end