% This is an autogenerated sample test for file createOrthonormalSystem.m
classdef testcreateOrthonormalSystem < matlab.unittest.TestCase

    methods (Test)

        function test_createOrthonormalSystem_for_basic_setup(testCase)
            % Specify the input(s) of
            % createOrthonormalSystem
            z = [0,0,1];
            % Specify the expected output(s) of
            % createOrthonormalSystem
            expected_x1 = [1,0,0];
            expected_y1 = [0,1,0];
            expected_z1 = [0,0,1];

            % Exercise the function createOrthonormalSystem
            [actual_x1, actual_y1, actual_z1] = createOrthonormalSystem(z);

            testCase.verifyEqual(actual_x1, expected_x1);
            testCase.verifyEqual(actual_y1, expected_y1);
            testCase.verifyEqual(actual_z1, expected_z1);
        end
        
        function test_vectors_are_orthonormal_for_random_case(testCase)
            z = [0.32,-0.134,0.452];

            [x1,y1,z1] = createOrthonormalSystem(z);
            tol = 1e-6;
            testCase.verifyLessThanOrEqual(abs(vecnorm(x1)-1.0),tol)
            testCase.verifyLessThanOrEqual(abs(vecnorm(y1)-1.0),tol)
            testCase.verifyLessThanOrEqual(abs(vecnorm(z1)-1.0),tol)

            testCase.verifyLessThanOrEqual(abs(cross(x1,y1)-z1),tol);
            testCase.verifyLessThanOrEqual(abs(cross(y1,z1)-x1),tol);
            testCase.verifyLessThanOrEqual(abs(cross(z1,x1)-y1),tol);
            testCase.verifyLessThanOrEqual(abs(cross(y1,x1)+z1),tol);
            
        end
    end
end