% This is an autogenerated sample test for file HexagonalPrism.m
classdef testHexagonalPrism < matlab.unittest.TestCase

    properties(TestParameter)
        basename = {...
            "particle_r_1_t_1_c_0_0_0_n_0_0_1.stl",...
            "particle_r_2_t_3_c_0_0_0_n_0_1_0.stl" ,...
            };
    end

    methods (Test)
        function test_canInstantiateHexagonalPrism(testCase)
            % Specify the input(s) of
            % HexagonalPrism
            normal = [1,1,1];
            faceRotation = [1,2,3];
            position = [-8049.1919,-4430.0356,937.63038];
            radius = 9575.0684;
            thickness = 9648.8854;


            % Exercise the function HexagonalPrism
            actual_obj = HexagonalPrism(position, radius, thickness, normal, faceRotation);

            % dummy statement just to exercise the call above
            testCase.verifyTrue(true);

        end

    end
end