% This is an autogenerated sample test for file vecnormalize.m
classdef testvecnormalize < matlab.unittest.TestCase

    methods (Test)

        function test_vecnormalize(testCase)
            in = [6294.4737,8115.8387,-7460.2637,8267.5171,2647.1849];

            % Specify the expected output(s) of
            % vecnormalize
            expected_out = 1.0;

            % Exercise the function vecnormalize
            actual_out = vecnorm(vecnormalize(in));

            tol = 1e-6;
            testCase.verifyLessThanOrEqual(abs(actual_out-expected_out),tol);
        end
    end
end