% This is an autogenerated sample test for file ExtractedPacking.m
classdef testExtractedPacking < matlab.unittest.TestCase

    properties (TestParameter)
        testFile = {
            "packing_parameters_5_4_success.stl",...
            "packing_parameters_15_1_success.stl",...
            "particles_100.stl",...
            "particles_200.stl",...

            }
        direction = {"x","y","z"}
        margin = {0,0.5,0.1,0.15,0.2,0.25,0.3}
    end

    methods (Test)

        function test_ExtractedPacking(testCase,testFile,direction,margin)

            testFileDir = fullfile(projectDir,"tests","test_stl_files");
            filename = fullfile(testFileDir,testFile);
            e = STLExtractor(filename,[]);
            ep = e.process();


            new_ep = ep.cutoff(margin,direction);

            radii = arrayfun(@(hp) hp.radius,ep.items);
            tol = max(radii);

            switch direction
                case "x"
                    Lold = ep.Lx;
                    Lnew = new_ep.Lx;
                case "y"
                    Lold = ep.Ly;
                    Lnew = new_ep.Ly;
                case "z"
                    Lold = ep.Lz;
                    Lnew = new_ep.Lz;
            end

            % check that cutoff actually remove margin
            testCase.verifyLessThanOrEqual( ...
                abs(Lnew - Lold*(1-margin)),tol)

            % verify that cutoff produce a cube
            testCase.verifyLessThanOrEqual( ...
                abs(new_ep.Lx - new_ep.Ly),tol)
            testCase.verifyLessThanOrEqual( ...
               abs(new_ep.Lz - new_ep.Ly),tol)

            % check alignments between 0 and 1

            testCase.verifyLessThanOrEqual( ...
                ep.volumetricFillingFraction,1.0)
            testCase.verifyLessThanOrEqual( ...
                ep.averageAlignmentX,1.0)
            testCase.verifyLessThanOrEqual(ep.volumeWeightedAverageAlignmentX,1.0)
            testCase.verifyLessThanOrEqual(ep.averageAlignmentY,1.0)
            testCase.verifyLessThanOrEqual(ep.volumeWeightedAverageAlignmentY,1.0)
            testCase.verifyLessThanOrEqual(ep.averageAlignmentZ ,1.0)
            testCase.verifyLessThanOrEqual(ep.volumeWeightedAverageAlignmentZ ,1.0)

            % positive quantities
            testCase.verifyGreaterThanOrEqual( ...
                ep.volumetricFillingFraction,0.0)
            testCase.verifyGreaterThanOrEqual( ...
                ep.averageAlignmentX,0.0)
            testCase.verifyGreaterThanOrEqual(ep.volumeWeightedAverageAlignmentX,0.0)
            testCase.verifyGreaterThanOrEqual(ep.averageAlignmentY,0.0)
            testCase.verifyGreaterThanOrEqual(ep.volumeWeightedAverageAlignmentY,0.0)
            testCase.verifyGreaterThanOrEqual(ep.averageAlignmentZ ,0.0)
            testCase.verifyGreaterThanOrEqual(ep.volumeWeightedAverageAlignmentZ ,0.0)
            testCase.verifyGreaterThanOrEqual(ep.volumeWeightedStandardDeviationAlignmentZ ,0.0)


            testCase.verifyGreaterThanOrEqual( ...
                ep.volume,0.0)
            testCase.verifyGreaterThanOrEqual(ep.standardDeviationAlignmentX,0.0)
            testCase.verifyGreaterThanOrEqual(ep.volumeWeightedStandardDeviationAlignmentX,0.0)
            testCase.verifyGreaterThanOrEqual(ep.standardDeviationAlignmentY,0.0)
            testCase.verifyGreaterThanOrEqual(ep.volumeWeightedStandardDeviationAlignmentY,0.0)
            testCase.verifyGreaterThanOrEqual(ep.standardDeviationAlignmentZ,0.0)
            testCase.verifyGreaterThanOrEqual(ep.volumeWeightedStandardDeviationAlignmentZ,0.0)

        end
        
    end
end