% This is an autogenerated sample test for file STLExtractor.m
classdef testSTLExtractor < matlab.unittest.TestCase

    properties (TestParameter)
       nParticles = {48,100,200};
    end

    methods (Test)

        function test_process_can_identify_number_of_triangles(testCase,nParticles)
            % Specify the input(s) of
            % STLExtractor
            projectDir = currentProject().RootFolder;
            testFileDir = fullfile(projectDir,"tests","test_stl_files");

            workingDir = "test_output";


            for i = nParticles
                filename = fullfile(testFileDir,['particles_',num2str(i),'.stl']);
                e = STLExtractor(filename,workingDir);
                % Exercise the function obj.process
                l = e.process();

                testCase.verifyEqual(numel(l), i);

            end


        end
    end
end